# Copied from https://coderefinery.github.io/documentation/gh_workflow/ and
# modified to use the GitHub Actions sphinx-build action
name: docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install sphinx numpydoc versioneer pandas xarray pyyaml numba
      - name: Sphinx build
        run: |
          sphinx-apidoc -o docsrc deltacd
          sphinx-build docsrc docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
